name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          zip unzip openjdk-17-jdk wget \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libgl1-mesa-dev libgles2-mesa-dev \
          libffi-dev libssl-dev

    - name: Install Android SDK Command Line Tools
        run: |
           mkdir -p $HOME/android-sdk/cmdline-tools/latest
           cd $HOME/android-sdk
           wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
           unzip commandlinetools-linux-11076708_latest.zip
           mv cmdline-tools/* cmdline-tools/latest/
           rm -rf cmdline-tools

    - name: Set Android SDK environment
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install Android SDK components (AIDL fix)
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-31"

    - name: Install Buildozer & python-for-android
      run: |
        pip install --upgrade pip
        pip install buildozer==1.5.0 python-for-android==2023.09.16 "cython<3.0"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-a
